// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKoiOCFQZT8pSlkENUBK4r4vdOIGf3x0A',
    appId: '1:822142000232:web:ccdcb67883395d454defdd',
    messagingSenderId: '822142000232',
    projectId: 'cine-stream-taller2',
    authDomain: 'cine-stream-taller2.firebaseapp.com',
    databaseURL: 'https://cine-stream-taller2-default-rtdb.firebaseio.com', 
    storageBucket: 'cine-stream-taller2.firebasestorage.app',
    measurementId: 'G-ZCNMYK0Z6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Ib3b7Ww13MqrNK5DWiY8KtMXL5p8-XM',
    appId: '1:822142000232:android:d0e6fdfa6f2565904defdd',
    messagingSenderId: '822142000232',
    projectId: 'cine-stream-taller2',
    databaseURL: 'https://cine-stream-taller2-default-rtdb.firebaseio.com', // 
    storageBucket: 'cine-stream-taller2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKoiOCFQZT8pSlkENUBK4r4vdOIGf3x0A',
    appId: '1:822142000232:web:1546bf267d4be2514defdd',
    messagingSenderId: '822142000232',
    projectId: 'cine-stream-taller2',
    authDomain: 'cine-stream-taller2.firebaseapp.com',
    databaseURL: 'https://cine-stream-taller2-default-rtdb.firebaseio.com', // 
    storageBucket: 'cine-stream-taller2.firebasestorage.app',
    measurementId: 'G-QC669SDYJX',
  );
}